version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8082"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./logs:/usr/src/app/logs

networks:
  default:
    name: mynetwork